In [17]:
import pandas as pd
from sklearn import datasets
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from algorythms import mlp
import numpy as np

# Датасет "Фильмы"

## Загрузка датасета

In [18]:
data = pd.read_csv('../data/CSM_snake_case.csv', sep = ',')

In [19]:
data

Movie    Year  Ratings  Genre        Gross       Budget  \
0                   13 Sins  2014.0      6.3    8.0       9130.0    4000000.0   
1            22 Jump Street  2014.0      7.1    1.0  192000000.0   50000000.0   
2            3 Days to Kill  2014.0      6.2    1.0   30700000.0   28000000.0   
3    300: Rise of an Empire  2014.0      6.3    1.0  106000000.0  110000000.0   
4         A Haunted House 2  2014.0      4.7    8.0   17300000.0    3500000.0   
..                      ...     ...      ...    ...          ...          ...   
226                Child 44  2015.0      6.4    4.0    1210000.0   50000000.0   
227                   Aloha  2015.0      5.5   15.0   21000000.0   37000000.0   
228     Unfinished Business  2015.0      5.4    8.0   10200000.0   35000000.0   
229                War Room  2015.0      5.4    1.0   12300000.0    3000000.0   
230             The Gallows  2015.0      4.4   15.0   22600000.0     100000.0   

         Screens  Sequel  Sentiment      Views    Likes  Dislikes  Comments  \
0      45.000000     1.0        0.0  3280543.0   4632.0     425.0     636.0   
1    3306.000000     2.0        2.0   583289.0   3465.0      61.0     186.0   
2    2872.000000     1.0        0.0   304861.0    328.0      34.0      47.0   
3    3470.000000     2.0        0.0   452917.0   2429.0     132.0     590.0   
4    2310.000000     2.0        0.0  3145573.0  12163.0     610.0    1082.0   
..           ...     ...        ...        ...      ...       ...       ...   
226    66.000000     1.0        4.0  3701061.0   9325.0     641.0    1859.0   
227  2815.000000     1.0       13.0  7119456.0  18803.0    1128.0    2290.0   
228  2777.000000     1.0        7.0  3450614.0   6823.0     325.0     409.0   
229  2209.244344     1.0       10.0    66872.0    400.0      67.0     201.0   
230  2720.000000     1.0       -5.0   659772.0   2841.0     431.0     606.0   

     Aggregate Followers  
0           1.120000e+06  
1           1.235000e+07  
2           4.830000e+05  
3           5.680000e+05  
4           1.923800e+06  
..                   ...  
226         3.038193e+06  
227         3.038193e+06  
228         3.038193e+06  
229         3.038193e+06  
230         3.038193e+06  

[231 rows x 14 columns]

## Подготовка датасета

In [20]:
data.drop('Movie', axis=1, inplace=True)
data

Year  Ratings  Genre        Gross       Budget      Screens  Sequel  \
0    2014.0      6.3    8.0       9130.0    4000000.0    45.000000     1.0   
1    2014.0      7.1    1.0  192000000.0   50000000.0  3306.000000     2.0   
2    2014.0      6.2    1.0   30700000.0   28000000.0  2872.000000     1.0   
3    2014.0      6.3    1.0  106000000.0  110000000.0  3470.000000     2.0   
4    2014.0      4.7    8.0   17300000.0    3500000.0  2310.000000     2.0   
..      ...      ...    ...          ...          ...          ...     ...   
226  2015.0      6.4    4.0    1210000.0   50000000.0    66.000000     1.0   
227  2015.0      5.5   15.0   21000000.0   37000000.0  2815.000000     1.0   
228  2015.0      5.4    8.0   10200000.0   35000000.0  2777.000000     1.0   
229  2015.0      5.4    1.0   12300000.0    3000000.0  2209.244344     1.0   
230  2015.0      4.4   15.0   22600000.0     100000.0  2720.000000     1.0   

     Sentiment      Views    Likes  Dislikes  Comments  Aggregate Followers  
0          0.0  3280543.0   4632.0     425.0     636.0         1.120000e+06  
1          2.0   583289.0   3465.0      61.0     186.0         1.235000e+07  
2          0.0   304861.0    328.0      34.0      47.0         4.830000e+05  
3          0.0   452917.0   2429.0     132.0     590.0         5.680000e+05  
4          0.0  3145573.0  12163.0     610.0    1082.0         1.923800e+06  
..         ...        ...      ...       ...       ...                  ...  
226        4.0  3701061.0   9325.0     641.0    1859.0         3.038193e+06  
227       13.0  7119456.0  18803.0    1128.0    2290.0         3.038193e+06  
228        7.0  3450614.0   6823.0     325.0     409.0         3.038193e+06  
229       10.0    66872.0    400.0      67.0     201.0         3.038193e+06  
230       -5.0   659772.0   2841.0     431.0     606.0         3.038193e+06  

[231 rows x 13 columns]

In [21]:
y = data['Year'].values
X = data.drop('Year', axis=1).values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y)

## Классификация с помощью модели MLP

In [22]:
model = mlp.MLP(inputs_count=X_train.shape[1], hidden_layers_counts_with_act_funcs=[(15, mlp.ActivationFunctions.sigmoid, mlp.ActivationFunctions.sigmoid_derivative), (15, mlp.ActivationFunctions.sigmoid, mlp.ActivationFunctions.sigmoid_derivative)]).fit(X_train, y_train, epochs=600, learning_rate=0.25)

object


E:\ML\MLOmSTUCourse\algorythms\mlp.py:9: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-x))


In [23]:
y_pred = []
for i in range(len(X_test)):
    prediction = model.predict(X_test[i])[0]
    if prediction > 0.5:
        y_pred.append(1)
    else:
        y_pred.append(0)

In [24]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 0  0  0]
 [33  0  0]
 [14  0  0]]
              precision    recall  f1-score   support

         1.0       0.00      0.00      0.00       0.0
      2014.0       0.00      0.00      0.00      33.0
      2015.0       0.00      0.00      0.00      14.0

    accuracy                           0.00      47.0
   macro avg       0.00      0.00      0.00      47.0
weighted avg       0.00      0.00      0.00      47.0



c:\users\dream\appdata\local\programs\python\python39\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\dream\appdata\local\programs\python\python39\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\dream\appdata\local\programs\python\python39\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, 

# Датасет "IRIS"

## Загрузка датасета

In [25]:
iris = datasets.load_iris()

## Подготовка датасета

In [26]:
X = iris.data
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [27]:
y = iris.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y)

In [29]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

## Классификация с помощью модели MLP

In [30]:
model = mlp.MLP(inputs_count=X_train.shape[1], hidden_layers_counts_with_act_funcs=[(3, mlp.ActivationFunctions.sigmoid, mlp.ActivationFunctions.sigmoid_derivative),
                                                                      (3, mlp.ActivationFunctions.sigmoid, mlp.ActivationFunctions.sigmoid_derivative)],
                outputs_count_with_act_funcs=[(3, mlp.ActivationFunctions.sigmoid, mlp.ActivationFunctions.sigmoid_derivative)])\
    .fit(X_train, y_train, epochs=300, learning_rate=0.15)

object


In [31]:
y_pred = []
for i in range(len(X_test)):
    y_pred.append(np.argmax(model.predict(X_test[i])))

In [32]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 0  0 10]
 [ 0  9  1]
 [ 0  0 10]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        10
           1       1.00      0.90      0.95        10
           2       0.48      1.00      0.65        10

    accuracy                           0.63        30
   macro avg       0.49      0.63      0.53        30
weighted avg       0.49      0.63      0.53        30



c:\users\dream\appdata\local\programs\python\python39\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\dream\appdata\local\programs\python\python39\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\dream\appdata\local\programs\python\python39\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo

# Выводы

* Выполнена своя реализация многослойного персептрона
* Модель протестирована на рекомендуемых датасетах
* Качество классификации получилось немного хуже, чем при использовании базовых моделей
* С большой вероятностью это связано с особенностями реализации (это действительно сложное задание)